### ISSUE TITLE
Please provide release tags for known working releases

### ISSUE THREAD

**Issue by truedat101** [Maratyszcza/NNPACK#108]
To assist projects that depend on NNPACK, it is a great value to OSS project builders to have tags associated with the project when releases are considered "done" and tested through validation processes.  Nice to have are release notes accompanying to have a limited changelog of things in each successive release.  I normally generate release notes using git commit refs using tags.  Thanks.   As far as tags, keeping it simple using semver 1.0.0, 1.1.0, etc. is nice.  Or something like release1, release2, etc.

**Comment by Maratyszcza** [comment]
No plans to do versioning, for several reasons:
1. The version in `master` is always considered release-ready. It runs through CI, but there is no additional validation process.
2. NNPACK API is not stable (albeit there are plans to stabilize it, see #24).
3. Due to limited time, I can't back-port bug fixes and performance optimizations to older NNPACK versions.

In other words, downstream libraries would have to pin NNPACK version themselves, or always use `master`. In the letter case, I can ping you when I'm about to land API-breaking changes.
