### ISSUE TITLE
Tagged release?

### ISSUE THREAD

**Issue by jakirkham** [Maratyszcza/NNPACK#13]
Would be nice to know where we can build from safely. A formal tagged release would be helpful in that effort. Though not sure how complete this is.

**Comment by Maratyszcza** [comment]
Master branch is expected to be stable at all times

**Comment by jakirkham** [comment]
Ok, could we please have a tag at least to know what API we can reliably use (and know when that changes)?

**Comment by Maratyszcza** [comment]
Generally, functions are usable iff they are documented. I can't guarantee API stability at this stage, but I don't break it without a good reason.

**Comment by ajtulloch** [comment]
@Maratyszcza  wouldn't some kind of versioning be useful for the BVLC/Caffe integration? So we can conditionally compile new layers as you implement the functions? It seems like the CuDNN model is reasonable to follow here?

**Comment by Maratyszcza** [comment]
@ajtulloch NNPACK is not packaged in Linux distros (and unlikely to be, due to its specific hardware requirements). Thus, users are expected to use the recent branch from GitHub.

In this situation versioning NNPACK would provide no benefits, but would task me with release management and potentially back-porting bug-fixes.
