### ISSUE TITLE
problem about NACL

### ISSUE THREAD

**Issue by zhaishengfu** [Maratyszcza/NNPACK#20]
dear Maratyszcza,
 i am using nacl sdk .i have reconfigure and build it. at last it succeeds and compiled the following programs under /web directory
![000](https://cloud.githubusercontent.com/assets/7630101/16295744/19ca870e-395b-11e6-81eb-8846608969fd.png)

now i wonder how to start the program of nacl. when i open the html file directly, it will show the following information:
![000](https://cloud.githubusercontent.com/assets/7630101/16295769/40867768-395b-11e6-94d3-7cccc5b01537.png)
you can see that native client not available. do you know the problem?? looking forward to your reply

**Comment by zhaishengfu** [comment]
i have change the browser to google and change the configuration of nnpack.nmf, now it changes to "Waiting for NNPACK module", i also see google native client tutorialm, but still dont know how to start the program. as i know, it is waiting for "load" and "progress" event, but how can i generate those events to make the html listen??

**Comment by Maratyszcza** [comment]
1. You have to use Google Chrome. Other browsers don't support this technology.
2. The Web demo you are trying to use was switched to PNaCl, rather than NaCl. Unlike NaCl, PNaCl is enabled by default in the Google Chrome. Unfortunately, it is also about 4x slower than NaCl.
3. You need to serve the Web demo through a Web server. Opening the HTML file locally wouldn't work. If you just want to look at performance of PNaCl implementation on your machine, try [this demo page](https://maratyszcza.github.io/NNPACK/nnpack.html)

**Comment by zhaishengfu** [comment]
Thanks to your reply!!
I know it should be chrome , after change to chrome, the error is as below:
![000](https://cloud.githubusercontent.com/assets/7630101/16303273/6882d3b6-3982-11e6-8ac8-ae059b495d8c.png)

but why can't NACI?? i found that under /bin directory there are many .nexe compiled files(each with original compiled programming),
![000](https://cloud.githubusercontent.com/assets/7630101/16303368/d9d1bd52-3982-11e6-8419-4876614813cd.png)

 Are they all of no use????besides, i want to use NACI because i want **accurate** c/c++ running time and i think this tool is **convenient for me to change the parameters** and see the time. If i can only use PNaCI and it is slower than NaCI, does the web time have any meaning???as you said,  i think the only method for me to have the accurate time of runing will be Command line as below:
![000](https://cloud.githubusercontent.com/assets/7630101/16302972/a53e276c-3980-11e6-8a4f-f4808bb56c32.png)
if this is the case, why you  said in ReadME as following:
- Configure NNPACK with `--host=x86_64-nacl-glibc` or `--host=x86_64-nacl-newlib` (recommended) option.
I used the recommended command with `--host=x86_64-nacl-newlib`. 


So , Do I misunderstand your meaning??with my understanding, your meaning is:
1. I can't use NACI and can only use PNACI. 
2. PNacI is alwalys slower than the actual pure c/c++ programming running. So , what can the time shown in your web demo illustrate?? My meaning is that PNACI may add some google native client time to it so it can't tell us anything about the real and accurate c/c++ runing time
3. Your code don't offer the ability to build a Web server for the html to run. I need extra work to run your html sample

**Comment by Maratyszcza** [comment]
Do you actually need to use NNPACK inside a Web browser? If no, just build the native binary for your system (`./configure.py && ninja`), and use command-line programs from `bin` directory to benchmark. They let you change parameters via command-line arguments.

**Comment by zhaishengfu** [comment]
ok. I just think your web demo is convenient to change the parameter. 
Thanks to your patient answer.

**Comment by Maratyszcza** [comment]
The Web demo is intended to demonstrate working NNPACK inside a Web browser. It is not intended to be a convenient interface for benchmarking for two reasons:

1. NNPACK running inside a Web browser is slower than native version, because of special sandboxing the code needs to do to satisfy security constraints of a browser. For convolution, the slowdown is about 2x when using NaCl and about 8x when using PNaCl.

2. Modern browsers run many extra threads in background, which interfere with parallelization inside NNPACK, and make time measurements noisy.

If you goal is not to run inside a web browser, don't. The command-line programs in the `bin` directory provide a convenient way to benchmark NNPACK at full speed. There is also `benchmark.py` script which tests typical layer configurations.

**Comment by zhaishengfu** [comment]
Thank you very much. Now  I know more about google native client and your NNPACK. You are really helpful and patient.
