### ISSUE TITLE
error :_pygit2.GitError: there is no TLS stream available

### ISSUE THREAD

**Issue by janelu9** [Maratyszcza/NNPACK#53]
when I build NNPACK on Ubuntu, it errored  when run " confu setup"

**Comment by Maratyszcza** [comment]
The problem is due to `libgit2` on Debian/Ubuntu built without HTTPS support. See [install_deps.sh](https://github.com/Maratyszcza/confu/blob/master/install_deps.sh) in confu repo, which will build libgit2 and pygit2 from sources. Make sure you uninstall your system `pygit2` (which is linked to system libgit2).
